### ISSUE TITLE
Zebra prints text of control characters

### ISSUE THREAD

**Issue by dakoller** [mchobby/PythonPcl#3]
Hi,

the python-pcl scripts print text on my Zebra LP2844,... but it brings up the control characters

like "XA...F0100"...

any idea, what is wrong?

Kind regards,

Daniel

**Comment by mchobby** [comment]
It is because the operating system did interpret the control characters and did escape it.
You have to install the printer as RAW printer. So everything send to the printer spooler is communicated as it to the printer!
